places_to_visit = ["Azerbaijan","Saudi Arabia","Norway","America","Iran"]
print("Original Order:")
print(places_to_visit)
print("\nAlphabetical Order (sorted()):")
print(sorted(places_to_visit))
print("\nOriginal Order (after sorted()):")
print(places_to_visit)
print("\nReverse Alphabetical Order (sorted()):")
print(sorted(places_to_visit, reverse=True))
print("\nOriginal Order (after sorted() with reverse=True):")
print(places_to_visit)
places_to_visit.reverse()
print("\nReversed Order:")
print(places_to_visit)
places_to_visit.reverse()
print("\nOriginal Order (after reverse() twice):")
print(places_to_visit)
places_to_visit.sort()
print("\nAlphabetical Order (sort()):")
print(places_to_visit)
places_to_visit.sort(reverse=True)
print("\nReverse Alphabetical Order (sort(reverse=True)):")
print(places_to_visit),